OBJ=multi_SIGCHLD
multi_SIGCHLD: multi_SIGCHLD.c
	gcc -o multi_SIGCHLD multi_SIGCHLD.c error_functions.c get_num.c curr_time.c print_wait_status.c

wating-for-childrens:wating-for-childrens.c
	gcc -o wating-for-childrens wating-for-childrens.c error_functions.c get_num.c curr_time.c print_wait_status.c

clean:
	rm multi_SIGCHLD *.o
